# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8iDBgy4mpAifHiNlrqT7FZzuyIW2fns
"""

A=int(input())
B=int(input())
if (A>B):
  for i in range(B,A+1):
    print(i)
elif (B>A):
    for i in range(A,B+1):
      print(i)
else:
  print("numbers are the same")