# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135AF3JiPLbFR_n8uYD7Otra3iZOaHiMo
"""

A=int(input())
B=int(input())
for i in range(A,B+1):
  s=str(i)
  rev=s[::-1]
  if s==rev:
    print(s, end=" ")